accounts/urls.py
from django.urls import path, include
from .import views
app_name = 'accounts'


urlpatterns = [
    path('addaccount', views.createAccount, name='addaccount'),
    path('accountview', views.accountview, name='accountview'),
    path('update_account/<id>/', views.updateaccount, name="updateaccount"),
    path('delete_account/<id>/', views.deleteaccount, name='deleteaccount'),
    path('home/', views.home, name='abc'),
    path('comments', views.commentview,  name='commentview'),
    path('addcomment', views.addcomment, name='addcomment'),
    path('update_comment/<id>/', views.updatecomment, name="updatecomment"),
    path('delete_comment/<id>/', views.deletecomment, name='deletecomment'),

    path('instabotcode', views.instabotcode, name='instabotcode'),
    path('login', views.login_view, name='login'),
    path('logout/', views.logout_views, name='logout'),
    path('report/', views.reportview, name='report'),
    path('error_message/', views.errormessage, name='ErrorMessage'),

]

insta_bot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accountviews


from insta_bot import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',accountviews.home),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# Create your models here.
from django.db import models


# Create your models here.
class Account(models.Model):
    userid = models.TextField(max_length=50, default=None, blank=True)
    password = models.TextField(max_length=50, default=None, blank=True)
    status = models.IntegerField( default=1, blank=True)

    def __str__(self):
        return self.userid



class Profile(models.Model):
    # account = models.ForeignKey(Account,on_delete=models.CASCADE, default=None,null=True)
    follow = models.BooleanField(default=0)
    comment =models.BooleanField(default=0)
    like = models.BooleanField(default=0)
    story = models.BooleanField(default=0)

class Comments(models.Model):
    title = models.TextField(max_length=100, default=None, blank=True)

accounts/forms.py
from django import forms
from . import models



class AddAccount(forms.ModelForm):
    class Meta:
        model = models.Account
        fields = ['userid', 'password','status']

    def __init__(self, *args, **kwargs):
        super(AddAccount, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = ' form-control'
            visible.field.widget.attrs['style'] = 'height: 40px; width: 90%; resize:none'
            visible.field.widget.attrs['resize'] = 'none'
            visible.field.widget.attrs['max'] = '1'
            visible.field.widget.attrs['min'] = '0'



class AddComment(forms.ModelForm):
    class Meta:
        model = models.Comments
        fields = ['title']

    def __init__(self, *args, **kwargs):
        super(AddComment, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = ' form-control'
            visible.field.widget.attrs['style'] = 'height: 43px; width: width: 90%; resize:none'
            visible.field.widget.attrs['resize'] = 'none'

accounts/views.py
import random

import keyboard
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from selenium.webdriver import ActionChains
from selenium.webdriver.common.keys import Keys

from accounts.forms import AddAccount, AddComment
from accounts.models import Account, Comments, Profile
import time
from selenium import webdriver
from time import sleep
from django.contrib.auth.decorators import login_required
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC


# from selenium.common.exceptions import NoSuchElementException
@login_required(login_url='/accounts/login')
def createAccount(request):
    form = AddAccount()
    if request.method == 'POST':
        form = AddAccount(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:accountview')

    context = {'form': form}
    return render(request, 'accounts/addaccount.html', context)


@login_required(login_url='/accounts/login')
def updateaccount(request, id):
    acc = Account.objects.get(id=id)
    form = AddAccount(instance=acc)
    print(id)
    if request.method == 'POST':
        form = AddAccount(request.POST, instance=acc)
        if form.is_valid():
            form.save()
            return redirect('accounts:accountview')

    context = {'form': form}
    return render(request, 'accounts/updateaccount.html', context)


@login_required(login_url='/accounts/login')
def accountview(request):
    acc = Account.objects.all()
    return render(request, 'accounts/accountsview.html', {'acc': acc})


@login_required(login_url='/accounts/login')
def deleteaccount(request, id):
    obj = get_object_or_404(Account, id=id)
    obj.delete()
    return accountview(request)


@login_required(login_url='/accounts/login')
def home(request):
    accounts = Account.objects.filter(status=1)
    maximum = len(accounts)
    return render(request, 'accounts/index.html', { 'maximum': maximum})


@login_required(login_url='/accounts/login')
def addcomment(request):
    form = AddComment()
    if request.method == 'POST':
        form = AddComment(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:commentview')

    context = {'form': form}
    return render(request, 'accounts/addcomment.html', context)


@login_required(login_url='/accounts/login')
def updatecomment(request, id):
    acc = Comments.objects.get(id=id)
    form = AddComment(instance=acc)
    print(id)
    if request.method == 'POST':
        form = AddComment(request.POST, instance=acc)
        if form.is_valid():
            form.save()
            return redirect('accounts:commentview')

    context = {'form': form}
    return render(request, 'accounts/updatecomment.html', context)


@login_required(login_url='/accounts/login')
def commentview(request):
    comment = Comments.objects.all()
    return render(request, 'accounts/commentview.html', {'comment': comment})


@login_required(login_url='/accounts/login')
def deletecomment(request, id):
    obj = get_object_or_404(Comments, id=id)
    obj.delete()
    return commentview(request)


def logout_views(request):
    if request.method == 'POST':
        print("-------------")
        logout(request)
        return render(request, 'accounts/newlogin.html')


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)

            # if 'next' in request.POST:
            #     return redirect(request.POST.get('next'))
            return redirect('accounts:abc')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/newlogin.html', {'form': form})


def reportview(request):
    return render(request, 'accounts/report.html')

def errormessage(request):
    return render(request,'accounts/error_message.html')


@login_required(login_url='/accounts/login')
def instabotcode(request):

    if request.method == 'POST':
        try:
            like = request.POST.get('liked')
            comment = request.POST.get('commented')
            story = request.POST.get('storyview')
            follow = request.POST.get('followed')
            accounts_no = request.POST.get('account_number_tag')
            like_report = 0
            comment_report = 0
            story_report = 0
            follow_report = 0
            acc_search = []
            acc_username = []
            acc_password = []
            comment_list = []
            comment = Comments.objects.all()
            accounts = Account.objects.filter(status=1)

            maximum = len(accounts)
            print(maximum)
            for com in comment:
                comment_list.append(com.title)
            # accounts.get(use)
            for acc in accounts:
                acc_username.append(acc.userid)
                acc_password.append(acc.password)

            print("-----------------")
            print(acc_username)
            print(acc_password)
            print("-----------------")
            print(random.choice(comment_list))
            if request.POST:
                target = request.POST.get('example-tags')
                acc_search = target.split(',')
                print(acc_search)
                for i in range(len(acc_search)):
                    print(acc_search[i])
                like = request.POST.get('liked')
                comment = request.POST.get('commented')
                story = request.POST.get('storyview')
                follow = request.POST.get('followed')
                pro = Profile(follow=follow, comment=comment, like=like, story=story)
                print(like)
                print(comment)
                print(story)
                print(follow)
                # pro.save()
            user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
            options = webdriver.ChromeOptions()
            options.headless = True
            options.add_argument(f'user-agent={user_agent}')
            options.add_argument("--window-size=1920,1080")
            options.add_argument('--ignore-certificate-errors')
            options.add_argument('--allow-running-insecure-content')
            options.add_argument("--disable-extensions")
            options.add_argument("--proxy-server='direct://'")
            options.add_argument("--proxy-bypass-list=*")
            options.add_argument("--start-maximized")
            options.add_argument('--disable-gpu')
            options.add_argument('--disable-dev-shm-usage')
            options.add_argument('--no-sandbox')
            driver = webdriver.Chrome(executable_path="chromedriver.exe", options=options)

            # chromepath = "chromedriver.exe"
            # driver = webdriver.Chrome(executable_path=chromepath)

            driver.get("chrome://settings/clearBrowserData")
            sleep(6)

            actions = ActionChains(driver)
            actions.send_keys(Keys.TAB * 7 + Keys.ENTER)
            actions.perform()
            keyboard.send("Enter")
            print('Cache Clear Successfully')
            driver.quit()


            # clearButton = driver.execute_script(
            #     "return document.querySelector('settings-ui').shadowRoot.querySelector('settings-main').shadowRoot.querySelector('settings-basic-page').shadowRoot.querySelector('settings-section > settings-privacy-page').shadowRoot.querySelector('settings-clear-browsing-data-dialog').shadowRoot.querySelector('#clearBrowsingDataDialog').querySelector('#clearBrowsingDataConfirm')")
            # # click on the clear button now
            # clearButton.click()


            # driver.findElement(By.name("s")).sendKeys(Keys.F5);

            # print(driver.title)
            # time.sleep(5)

            for login in range(int(accounts_no)):
                sleep(6)
                user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
                options = webdriver.ChromeOptions()
                options.headless = True
                options.add_argument(f'user-agent={user_agent}')
                options.add_argument("--window-size=1920,1080")
                options.add_argument('--ignore-certificate-errors')
                options.add_argument('--allow-running-insecure-content')
                options.add_argument("--disable-extensions")
                options.add_argument("--proxy-server='direct://'")
                options.add_argument("--proxy-bypass-list=*")
                options.add_argument("--start-maximized")
                options.add_argument('--disable-gpu')
                options.add_argument('--disable-dev-shm-usage')
                options.add_argument('--no-sandbox')
                driver = webdriver.Chrome(executable_path="chromedriver.exe", options=options)

                # chromepath = "chromedriver.exe"  # Headless
                # driver = webdriver.Chrome(executable_path=chromepath)

                driver.get('https://www.instagram.com/')

                wait = WebDriverWait(driver, 10)

                sleep(5)
                print('Webpage :' + driver.title)
                print("Username :" + acc_username[login])
                print("Password : " + acc_password[login])
                Username = WebDriverWait(driver, 10).until(EC.visibility_of_element_located(
                    (By.XPATH, "/html/body/div[1]/section/main/article/div[2]/div[1]/div/form/div/div[1]/div/label/input")))
                Username.send_keys(acc_username[login])
                sleep(1)

accounts/templates/accounts/accountsview.html
{% extends 'basetemplate 2.html' %}
{% block content %}
                    <!-- Page content -->
                    <div id="page-content">
                        <!-- First Row -->
                        <div class="row">

                        </div>

                        <div class="row">


                            <div class="container" >
      <div class="">
        <a href="{% url 'accounts:addaccount' %}" class="btn btn-info" style="float:right;MARGIN-RIGHT: 02%;" >Add Account</a>
        <br><br>
        {#        <h2>Create an Awesome New Article</h2>#}
        <table class="table table-bordered table-striped" style="background-color: white">
            <thead>
            <th>#</th>
            <th>UserName</th>
            <th>Password</th>
            <th>Actions</th>
            </thead>
            <tbody>
            {% for acc in acc %}
            <tr style="color: black">
                <td>{{ forloop.counter }}</td>
                <td>{{ acc.userid }}</td>
                <td>{{ acc.password }}</td>
                <td> <a href="{% url 'accounts:updateaccount' acc.id %}" style="background-color: #454E59; color: white" class="btn ">Update</a> <a href="{% url 'accounts:deleteaccount' acc.id %}" style="background-color: #CA0028; color: white" class="btn ">Delete</a>  </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

                        </div>
                        <!-- END Second Row -->


                    </div>

                    <!-- END Page Content -->
                </div>

{% endblock %}
                <!-- END Main Container -->

accounts/templates/accounts/addaccount.html
{% extends 'basetemplate 2.html' %}

   {% block content %}
                    <!-- Page content -->
                    <div id="page-content">
                        <!-- First Row -->
                        <div class="row">

                        </div>

                        <div class="row">


                            <div class="container" style="background-color: white; height: auto;">
  <form class="site-form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <label>Username</label>
        {{ form.userid }}
      <label>Password</label>
        {{ form.password }}
      <label>Active status</label>
      {{ form.status }}
        <input type="submit"  class="btn " style="background-color: #CA0028; color: white" value="Add">
    </form>
</div>

                        </div>
                        <!-- END Second Row -->


                    </div>

       {% endblock %}

accounts/templates/accounts/addaccountform.html
{% extends 'basetemplate 2.html' %}

   {% block content %}
                    <!-- Page content -->
                    <div id="page-content">
                        <!-- First Row -->
                        <div class="row">

                        </div>

                        <div class="row">


                            <div class="container" style="background-color: white; height: 200px;">
  <form class="site-form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <label>Username</label>
        {{ form.userid }}
      <label>Password</label>
        {{ form.password }}
        <input type="submit"  class="btn " style="background-color: #CA0028; color: white" value="Add">
    </form>
</div>

                        </div>
                        <!-- END Second Row -->


                    </div>

       {% endblock %}

accounts/templates/accounts/addcomment.html
{% extends 'basetemplate 2.html' %}
                    <!-- END Header -->
{% block content %}

                    <!-- Page content -->
                    <div id="page-content">
                        <!-- First Row -->
                        <div class="row">

                        </div>

                        <div class="row">


                            <div class="container" style="background-color: white; height: 200px;">
  <form class="site-form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <label>Comment</label>
        {{ form.title }}

        <input type="submit"  class="btn " style="background-color: #CA0028; color: white" value="Add">
    </form>
</div>

                        </div>
                        <!-- END Second Row -->


                    </div>

   {% endblock %}

accounts/templates/accounts/commentview.html
{% extends 'basetemplate 2.html' %}
                    <!-- END Header -->
{% block content %}
                    <!-- Page content -->
                    <div id="page-content">
                        <!-- First Row -->
                        <div class="row">

                        </div>

                        <div class="row">


                            <div class="container" >
      <div class="">
        <a href="{% url 'accounts:addcomment' %}" class="btn btn-info" style="float:right;MARGIN-RIGHT: 02%;" >Add Comment</a>
        <br><br>
        {#        <h2>Create an Awesome New Article</h2>#}
        <table class="table table-bordered table-striped" style="background-color: white">
            <thead>
            <th>Comment</th>
            <th>Action</th>

            </thead>
            <tbody>
            {% for comment in comment %}
            <tr style="color: black">
                <td>{{ comment.title }}</td>
                <td> <a href="{% url 'accounts:updatecomment' comment.id %}" style="background-color: #454E59; color: white" class="btn ">Update</a> <a href="{% url 'accounts:deletecomment' comment.id %}" style="background-color: #CA0028; color: white" class="btn ">Delete</a>  </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

                        </div>
                        <!-- END Second Row -->


                    </div>

                    <!-- END Page Content -->
                </div>


{% endblock %}
                <!-- END Main Container -->

accounts/templates/accounts/index.html
{% extends 'basetemplate 2.html' %}
{% load static %}

                    <!-- END Header -->
{% block content %}

            <!-- Page content -->
            <div id="page-content">
                <!-- First Row -->
                <div class="row">

                </div>

                <div class="row">

                    <div class="col-sm-12 col-lg-12">
                        <!-- Forum Block -->
                        <div class="block">
                            <!-- Forum Tabs Title -->
                            <div class="block-title">
                                <ul class="nav nav-tabs" data-toggle="tabs">
                                    <li class="active"><a href="#forum-categories">NAME</a></li>
                                </ul>
                            </div>
                            <!-- END Forum Tabs -->

                            <!-- Tab Content -->
                            <div class="tab-content">
                                <!-- Forum -->


                                <div class="tab-pane active" id="forum-categories">
                                    <h3 class="text-dark" style="font-weight: bold;">Dashboard</h3>
                                </div>

                                <form  action="{% url 'accounts:instabotcode' %}" method="post"  class="form-horizontal form-bordered" >
                                    {% csrf_token %}
                                    <!-- Jquery Tags Input (class is initialized in js/app.js -> uiInit()), for extra usage examples you can check out https://github.com/xoxco/jQuery-Tags-Input -->
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Enter Target Accounts</label>
                                        <div class="col-md-9">
                                            <input type="text" id="example-tags" name="example-tags" class="input-tags" value="abdulrahman_ijaz, qlla_by_nomi" >
                                        </div>
                                        <p style="font-size: x-small;margin-left: 30%;">Please, place at least 5-6 accounts competitors to target.</p>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Enter Number of Accounts</label>
                                        <div class="col-md-9">
                                            <input type="number" class=" form-control " min="1" value="{{ maximum }}" style="width: 350px; height: 35px" id="example-tag" name="account_number_tag"  placeholder="1,2, or more" max="{{ maximum }}" >
                                        </div>
                                        <p style="font-size: x-small;margin-left: 30%;">Please, enter value in numerical form</p>
                                    </div>


                                    <div class="form-group">
                                        <div class="tab-pane active" id="forum-categories" style="margin-left: 1%;">
                                            <h3 class="text-dark" style="font-weight: bold;">Options</h3>
                                        </div>
                                        <label class="col-md-3 control-label">Like</label>
                                        <div class="col-md-9">
                                            <label class="switch switch-info"><input name="liked" type="checkbox" value="1" ><span></span></label>
                                        </div>
                                        <label class="col-md-3 control-label">Comment</label>
                                        <div class="col-md-9">
                                            <label class="switch switch-info"><input name="commented" type="checkbox" value="1" ><span></span></label>
                                        </div>
                                        <label class="col-md-3 control-label">Follow</label>
                                        <div class="col-md-9">
                                            <label class="switch switch-info"><input name="followed" type="checkbox" value="1" ><span></span></label>
                                        </div>
                                        <label class="col-md-3 control-label">Watch Stories</label>
                                        <div class="col-md-9">

                                            <label class="switch switch-info"><input name="storyview" type="checkbox" value="1" ><span></span></label>
                                            <button style="margin-left: 700px" type="submit" id="load-button" class="btn btn-rounded btn-info text-center">Start Bot</button>

                                        </div>
                                    </div>
{#                                     <div class="col-md-3">#}
{#                                            <button type="submit" id="load-button" class="btn btn-rounded btn-info text-center">Start Bot</button>#}
{#                                        </div>#}
                                    <br>
                                    <br>
{#                                    <div class="form-group">#}
{##}
{#                                        <div class="col-md-3">#}
{#                                            <button type="submit" id="load-button" class="btn btn-rounded btn-info text-center">Start Bot</button>#}
{#                                        </div>#}
{#                                    </div>#}
                                </form>
                                <div class="loading-overlay">
                                    <img src="{% static 'loading.gif' %}">
                                </div>

                            </div>
                            <!-- END Tab Content -->
                        </div>
                        <!-- END Forum Block -->
                    </div>

                </div>
                <!-- END Second Row -->


            </div>

{% endblock %}
            <!-- END Page Content -->

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
 <html class="no-js" lang="en">
    <head>
    <script src="https://kit.fontawesome.com/81544578fb.js" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
        <meta charset="utf-8">

        <title>App - Admin</title>

        <meta name="description" content="AppUI is a Web App Bootstrap Admin Template created by pixelcave and published on Themeforest">
        <meta name="author" content="pixelcave">
        <meta name="robots" content="noindex, nofollow">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0">


        <link rel="shortcut icon" href="{% static 'favicon.png' %}">
        <link rel="apple-touch-icon" href="{% static 'icon57.png' %}" sizes="57x57">
        <link rel="apple-touch-icon" href="{% static 'icon72.png' %} " sizes="72x72">
        <link rel="apple-touch-icon" href="{% static 'icon76.png' %}" sizes="76x76">
        <link rel="apple-touch-icon" href="{% static 'icon114.png' %}" sizes="114x114">
        <link rel="apple-touch-icon" href="{% static 'icon120.png' %}" sizes="120x120">
        <link rel="apple-touch-icon" href="{% static 'icon144.png' %}" sizes="144x144">
        <link rel="apple-touch-icon" href="{% static 'icon152.png' %}" sizes="152x152">
        <link rel="apple-touch-icon" href="{% static 'icon180.png' %}" sizes="180x180">

        <link rel="stylesheet" href="{% static  'bootstrap.min.css'%}">

        <!-- Related styles of various icon packs and plugins -->
        <link rel="stylesheet" href="{% static 'plugins.css' %}">

        <!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
        <link rel="stylesheet" href="{% static 'main.css' %}">

        <!-- Include a specific file here from css/themes/ folder to alter the default theme of the template -->

        <!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
        <link rel="stylesheet" href="{% static 'themes.css' %}">
        <!-- END Stylesheets -->

        <!-- Modernizr (browser feature detection library) -->
        <script src="{% static 'modernizr-3.3.1.min.js' %}"></script>
    </head>
    <body>
        <img src="img/placeholders/layout/login2_full_bg.jpg" alt="Full Background" class="full-bg animation-pulseSlow">
        <!-- END Full Background -->

        <!-- Login Container -->
        <div id="login-container">
            <!-- Login Header -->
            <h1 class="h2 text-light text-center push-top-bottom animation-pullDown">
                <i class="fa fa-cube text-light-op"></i> <strong>AppName</strong>
            </h1>

            <div class="block animation-fadeInQuick">
                <!-- Login Title -->
                <div class="block-title">
                    <h2>Please Login</h2>
                </div>
                <!-- END Login Title -->

                <!-- Login Form -->
                <form id="form-login" method="post" action="{% url 'accounts:login' %}"  class="form-horizontal">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="login-email" class="col-xs-12">Email</label>
                        <div class="col-xs-12">
                            <input type="text" id="login-email" name="login-email" class="form-control" placeholder="Your email..">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="login-password" class="col-xs-12">Password</label>
                        <div class="col-xs-12">
                            <input type="password" id="login-password" name="login-password" class="form-control" placeholder="Your password..">
                        </div>
                    </div>
                    <div class="form-group form-actions">
                        <div class="col-xs-8">
                            <label class="csscheckbox csscheckbox-primary">
                                <input type="checkbox" id="login-remember-me" name="login-remember-me"><span></span> Remember Me?
                            </label>
                        </div>
                        <div class="col-xs-4 text-right">
                            <input type="submit"  class="btn btn-effect-ripple btn-sm btn-success" value="LOGIN">
                          <button type="submit" class="btn btn-effect-ripple btn-sm btn-success">Log In</button>
                        </div>
                    </div>
                </form>

                <hr>

            </div>

            <footer class="text-muted text-center animation-pullUp">
                <small><span id="year-copy"></span> &copy; <a href="#" target="_blank">AppName 0.1</a></small>
            </footer>
            <!-- END Footer -->
        </div>
        <!-- END Login Container -->

        <!-- jQuery, Bootstrap, jQuery plugins and Custom JS code -->
          <script src="{% static 'jquery-2.2.4.min.js' %}"></script>
        <script src="{% static 'bootstrap.min.js' %}"></script>
        <script src="{% static 'plugins.js' %}"></script>
        <script src="{% static 'app.js' %}"></script>

        <!-- Load and execute javascript code used only in this page -->
        <script src="js/pages/readyDashboard.js"></script>
        <script>$(function(){ ReadyDashboard.init(); });</script>
    </body>
</html>